### ISSUE TITLE
make xcvu3p.device throws java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by timakro** [Xilinx/fpga24_routing_contest#26]
Running `make xcvu3p.device` results in

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3481)
	at java.base/java.util.ArrayList.grow(ArrayList.java:237)
	at java.base/java.util.ArrayList.grow(ArrayList.java:244)
	at java.base/java.util.ArrayList.add(ArrayList.java:454)
	at java.base/java.util.ArrayList.add(ArrayList.java:467)
	at com.xilinx.rapidwright.interchange.DeviceResourcesWriter.writeAllWiresAndNodesToBuilder(DeviceResourcesWriter.java:828)
	at com.xilinx.rapidwright.interchange.DeviceResourcesWriter.writeDeviceResourcesFile(DeviceResourcesWriter.java:301)
	at com.xilinx.rapidwright.interchange.DeviceResourcesExample.main(DeviceResourcesExample.java:56)
	at com.xilinx.rapidwright.MainEntrypoint$$Lambda$16/0x000000080008d890.main(Unknown Source)
	at com.xilinx.rapidwright.MainEntrypoint.main(MainEntrypoint.java:223)
```

Workaround is to bypass the Makefile and `RapidWright/bin/rapidwright` scripts so we can set `-Xmx14g` or similar:

```
java -Xmx14g -jar RapidWright/build/libs/main.jar DeviceResourcesExample xcvu3p
```

**Comment by eddieh-xlnx** [comment]
Hi @timakro. Thanks for the report! It turns out that my machine has plenty of memory such that JVM's default max heap size was more than 14G and so this never came up during our testing.

The recommended way to inject JVM options into the `rapidwright` wrapper is:
```
_JAVA_OPTIONS="-Xmx14g" RapidWright/bin/rapidwright ...
```

Would you like to add a PR to modify this line to do this:
https://github.com/Xilinx/fpga24_routing_contest/blob/cdd0797799224f5701fd925b51a9ee7ecbd25aba/Makefile#L91
Or I can do it?

**Comment by eddieh-xlnx** [comment]
Alternatively, for anyone still struggling, I've recently added it as a release asset:
https://github.com/Xilinx/fpga24_routing_contest/releases/download/v1.1.1/xcvu3p.device

**Comment by timakro** [comment]
@eddieh-xlnx you can do it. Note that `14g` was an arbitrary pick, I'm not sure how much memory is required.

**Comment by eddieh-xlnx** [comment]
Sounds good; didn't want to deprive you of any due credit! Your arbitrary pick of `14g` is very reasonable -- it failed for me with `12g` so I've gone with that.
